export const GET_ACTIVIDAD = 'GET_ACTIVIDAD';
export const EDIT_ACTIVIDAD = 'EDIT_ACTIVIDAD';
export const CREATE_ACTIVIDAD = 'CREATE_ACTIVIDAD';
export const DELETE_ACTIVIDAD = 'DELETE_ACTIVIDAD';
export const FAILED_ACTIVIDAD = 'FAILED_ACTIVIDAD';
