export const TYPES = {
  CREATE_CATEGORIE: 'CREATE_CATEGORIE',
  GET_CATEGORIE: 'GET_CATEGORIE',
  GET_ALL_CATEGORIE: 'GET_ALL_CATEGORIE',
  EDIT_CATEGORIE: 'EDIT_CATEGORIE',
  DELETE_CATEGORIE: 'DELETE_CATEGORIE',
  ERROR: 'ERROR',
};
