export const GET_SLIDE_HOME = 'GET_SLIDE_HOME';
export const GET_SLIDE_BACKOFFICE = 'GET_SLIDE_BACKOFFICE';
export const EDIT_SLIDE = 'EDIT_SLIDE';
export const CREATE_SLIDE = 'CREATE_SLIDE';
export const DELETE_SLIDE = 'DELETE_SLIDE';
export const ACTION_FAILED = 'ACTION_FAILED';
export const GET_SINGLE_SLIDE_BACKOFFICE = 'GET_SINGLE_SLIDE_BACKOFFICE';
export const CLEAR_SINGLE_SLIDE = 'CLEAR_SINGLE_SLIDE';
